version: "2"
services:
    web_server:
        restart: always
        container_name: web_server
        build:
          context: .
          dockerfile: Dockerfile
        ports:
        - "80:80"
        # links:
        # - "node:node"


